### PR TITLE
Add a buf.yaml for Buf CLI compatibility

### PR DESCRIPTION
**Pull request by Alfus**
To control which files get synced to https://buf.build/cel/spec.

### CODE REVIEW

**Comment by Alfus** [comment]
To control which files get synced to buf.build.

**Comment by TristonianJones** [comment]
@Alfus does this help buf.build users more easily integrate with CEL?

**Comment by Alfus** [comment]
This does allow the buf CLI to run in the cel-spec repo, which allows for code gen, linting, etc. However, the real reason to include this file, is to control which .proto files descriptors should be uploaded to buf.build/cel/spec

**Review by TristonianJones — APPROVED** [review]

**Pull request merged**
