### PR TITLE
Fix spelling in code sample

### PR DESCRIPTION
**Pull request by goto-bus-stop**
`protbuf` -> `protobuf`

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
I signed the CLA with my github name but i don't have my google account email added on github. Will it work if i simply amend the commit with the author/committer email set to my google email, even if it's not added in github?

**Comment by TristonianJones** [comment]
Hi @goto-bus-stop! Honestly, I'm not sure how the CLA tool is tracking your association to GitHub. I can patch the commit if need be, but would prefer you get credit for the contribution.

**Comment by goto-bus-stop** [comment]
I amended the commit. Looks like it passes with my google email 🙂

**Review by TristonianJones — APPROVED** [review]

**Pull request merged**
