### PR TITLE
Add 'test all' definitions

### PR DESCRIPTION
**Pull request by Alfus**
To complete the set of local .proto definitions for the conformance tests. Note that the uri's of the Any's in the conformance test data will need to be updated to migrate to these definitions.

### CODE REVIEW

**Comment by Alfus** [comment]
Results in the following packages:
image

**Review by TristonianJones — APPROVED** [review]

**Comment by TristonianJones** [comment]
@Alfus running the bazel build locally seems to be fine. I'm not sure why Cloud Build is unhappy, but I'll merge soon and sort out the GCB issues separately given the local builds / tests seem fine.

**Pull request merged**
